# Generated by Django 5.1.5 on 2025-01-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articleposition_scope_articleposition_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleposition',
            name='quantity',
        ),
        migrations.AddField(
            model_name='articleposition',
            name='basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articleposition',
            name='chapter',
            field=models.CharField(max_length=100, null=True, verbose_name='Раздел'),
        ),
    ]
