# Generated by Django 5.1.5 on 2025-01-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_tag_alter_article_options_alter_scope_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={},
        ),
    ]
