GET http://127.0.0.1:8000/api/sensors/

###

POST http://127.0.0.1:8000/api/sensors/ 
Content-Type: application/json

{
    "name": "Panasonic",
    "description": "Датчик в детской"
}

###

PATCH http://127.0.0.1:8000/api/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

POST http://127.0.0.1:8000/api/measurements/
Content-Type: application/json

{
  "sensor": "1",
  "temperature": 22.3
}

###

GET http://127.0.0.1:8000/api/sensors/3/