# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков ЕСТЬ
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика ЕСТЬ
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика ЕСТЬ
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения ЕСТЬ
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.3
}

###

# получение информации по датчику ЕСТЬ
GET {{baseUrl}}/sensors/1/
Content-Type: application/json
