# Generated by Django 5.1.4 on 2025-01-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(editable=False, max_length=300, unique=True),
        ),
    ]
